### ISSUE TITLE
Indicate note value

### ISSUE THREAD

**Issue by jeandrek** [Jonathan50/harp-midi#1]
For some reason there are always two NOTE ON messages for each note and no NOTE OFF messages! Also I'll have to figure out how to actually get note value.

**Comment by jeandrek** [comment]
Well, I think that every second `note-on-message` for a note is actually a NOTE OFF message&hellip;

**Comment by jeandrek** [comment]
I'll also need the "pulses per quarter note" (crotchet) http://stackoverflow.com/questions/2467995/actual-note-duration-from-midi-duration#answer-2471045

Okay, ppqn is the same as the division (when positive), so I can use `midifile-division`.

**Comment by Jonathan50** [comment]
Okay, ppqn is the same as the division (when positive), so I can use `midifile-division`.

**Comment by jeandrek** [comment]
Also, I need to decide how to show note value. I'd love to be able to use Unicode music notes, but many of those don't show on my computer.

I think I'm going to use the number of beats (1/2 for quaver, 1 for crotchet, 2 for minim, etc.).

**Comment by jeandrek** [comment]
http://stackoverflow.com/questions/20770138/finding-the-duration-a-note-is-held-midi#answer-20805951

> Most likely, you won't find many **NoteOff** events, because the end of a note is often encoded as a **NoteOn** event with velocity zero. This allows to use the running status optimization, which avoids to repeat identical status bytes.

Oh.
